import { useQuery } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { api } from '../lib/api';
import type { Booking } from '../types';

export default function BookingConfirmation() {
  const { bookingId } = useParams();
  const { data, isLoading } = useQuery({ queryKey: ['booking', bookingId], enabled: Boolean(bookingId), queryFn: () => api.get<{ booking: Booking & { provider?: { name: string }; category?: { name: string } } }>(`/api/bookings/${bookingId}`) });
  return <div className="flex min-h-[70vh] items-center justify-center bg-[#f7fafb] px-5 py-12"><section className="w-full max-w-xl rounded-3xl border border-slate-100 bg-white p-8 text-center shadow-xl shadow-slate-200/60"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-teal-50 text-3xl text-primary">✓</div><p className="mt-6 text-sm font-semibold text-primary">REQUEST SENT</p><h1 className="mt-2 text-3xl font-bold text-slate-900">Booking confirmed</h1><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-slate-500">Your selected professional has received your request. We’ll keep you updated as the service progresses.</p>{isLoading ? <p className="mt-8 text-sm text-slate-500">Loading booking details…</p> : <div className="mt-8 rounded-2xl bg-slate-50 p-5 text-left"><p className="font-bold text-slate-900">{data?.booking.category?.name || 'Home service'}</p><p className="mt-2 text-sm text-slate-500">{data?.booking.address}</p><div className="mt-4 flex justify-between border-t border-slate-200 pt-4 text-sm"><span className="text-slate-500">Professional</span><span className="font-semibold text-slate-800">{data?.booking.provider?.name || 'Assigned shortly'}</span></div></div>}<div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to={`/track/${bookingId}`} className="flex-1 rounded-xl bg-primary px-5 py-3 font-semibold text-white transition hover:bg-teal-700">Track service</Link><Link to="/history" className="flex-1 rounded-xl border border-slate-200 px-5 py-3 font-semibold text-slate-700">View bookings</Link></div></section></div>;
}
