import { useQuery } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api } from '../lib/api';
import type { ProviderProfile } from '../types';

type ProfileDetail = ProviderProfile & { user: { name: string; phone: string } };

export default function ProviderProfilePage() {
  const { providerId } = useParams();
  const navigate = useNavigate();
  const { data, isLoading, error } = useQuery({ queryKey: ['provider', providerId], enabled: Boolean(providerId), queryFn: () => api.get<{ profile: ProfileDetail }>(`/api/providers/${providerId}`) });
  const profile = data?.profile;
  return <div className="bg-[#f7fafb] px-5 py-10 lg:px-8"><div className="mx-auto max-w-5xl"><button onClick={() => navigate(-1)} className="text-sm font-semibold text-primary">← Back to results</button>{isLoading && <p className="mt-8 text-slate-500">Loading professional profile…</p>}{error && <p className="mt-8 text-red-600">{(error as Error).message}</p>}{profile && <div className="mt-6 grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><section className="rounded-3xl border border-slate-100 bg-white p-7 shadow-sm"><div className="flex items-start gap-4"><div className="grid h-16 w-16 shrink-0 place-items-center rounded-2xl bg-teal-50 text-2xl text-primary">✦</div><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold text-slate-900">{profile.user.name}</h1><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700">Verified pro</span></div><p className="mt-1 text-slate-500">{profile.category} specialist</p><p className="mt-2 text-sm text-amber-500">★★★★★ <span className="text-slate-500">{profile.avgRating || 'New'} rating</span></p></div></div><div className="mt-8 border-t border-slate-100 pt-7"><h2 className="text-lg font-bold text-slate-900">About this professional</h2><p className="mt-3 leading-7 text-slate-600">A verified FixItNow professional, ready to help with reliable service and clear communication from request to completion.</p></div><div className="mt-8"><h2 className="text-lg font-bold text-slate-900">Skills & expertise</h2><div className="mt-4 flex flex-wrap gap-2">{profile.skills.map((skill) => <span key={skill} className="rounded-full bg-teal-50 px-3 py-2 text-sm font-medium text-primary">{skill}</span>)}</div></div></section><aside className="h-fit rounded-3xl border border-slate-100 bg-white p-6 shadow-sm"><p className="text-sm font-semibold text-primary">SERVICE DETAILS</p><h2 className="mt-2 text-xl font-bold text-slate-900">Book with confidence</h2><div className="mt-6 space-y-4 text-sm"><div className="flex justify-between border-b border-slate-100 pb-3"><span className="text-slate-500">Hourly rate</span><strong className="text-slate-900">₹{profile.hourlyRate}/hr</strong></div><div className="flex justify-between border-b border-slate-100 pb-3"><span className="text-slate-500">Response</span><strong className="text-slate-900">Usually quick</strong></div><div className="flex justify-between"><span className="text-slate-500">Verification</span><strong className="text-emerald-600">Complete</strong></div></div><Link to={`/book/${providerId}?category=${encodeURIComponent(profile.category)}`} className="mt-7 block rounded-xl bg-primary px-5 py-3 text-center font-semibold text-white transition hover:bg-teal-700">Book this specialist</Link></aside></div>}</div></div>;
}
